import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Elijah Bulluck
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";
        String title = "";
        int titleNum = getChildElement(channel, "title");

        String desc = "";
        int descNum = getChildElement(channel, "description");
        int linkNum = getChildElement(channel, "link");
        //title is assumed to already be a tag, so check if title has a text
        //child, if not print "Empty Title"
        if (channel.child(titleNum).numberOfChildren() > 0) {
            title = channel.child(titleNum).child(0).label();
        } else {
            title = "Empty Title";
        }
        //check if description has a text child and if not, print "No description"
        if (channel.child(descNum).numberOfChildren() > 0) {
            desc = channel.child(descNum).child(0).label();
        } else {
            desc = "No description";
        }
//print out html output like how contract says to
        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        //output the link
        out.println("<h1><a href = " + channel.child(linkNum).child(0).label()
                + "\">" + title + "</a></h1>");
        out.println("<p>" + desc + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th><strong>Date</strong></th>");
        out.println("<th><strong>Source</strong></th>");
        out.println("<th><strong>News</strong></th>");
        out.println("</tr>");
        //create a loop for the item tables that goes through all of the
        //children of channel to create the tables
        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                //use processItem method to make the tables
                processItem(channel.child(i), out);
            }
        }
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";
//output tags that are in the contract
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";
        //(from RSSProcessing lab)
        //returns the index of the tag if it is found (if statement),
        //and if not, return -1
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).label().equals(tag)) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";
        //start table row
        out.println("<tr>");
        //look for date and if not present, writes "No date available in the table
        int numDate = getChildElement(item, "pubDate");
        if (numDate == -1) {
            out.println("<td>No date available</td>");
        } else {
            //make if-statement for children because their still may be
            //a date tag, but it may have no text
            if (item.child(numDate).numberOfChildren() > 0) {
                out.println("<td>" + item.child(numDate).child(0).label()
                        + "</td>");
            } else {
                out.println("<td>No date available");
            }
        }
        //do the same as above for source with the addition of an attribute
        int numSource = getChildElement(item, "source");
        if (numSource == -1) {
            out.println("<td>No source available</td>");
        } else {
            //if there is a url, print the source with the url
            if (item.child(numSource).hasAttribute("url")) {
                out.println("<td><a href=\""
                        + item.child(numSource).attributeValue("url") + "\">"
                        + item.child(numSource).child(0).label() + "</td>");
            } else {
                //if there's no url, print the source with no link
                out.println("<td>" + item.child(numSource).child(0).label()
                        + "</td>");
            }
        }
        //print title OR description depending on which is found
        int titleNum = getChildElement(item, "title");
        int descNum = getChildElement(item, "description");
        int linkNum = getChildElement(item, "link");
        //start off with no title and then add to it if conditions are met
        String newsRow = "No title available";
        if (titleNum != -1) {
            //now check if title or description have a text child and if not,
            //keep the newRow the same
            if (item.child(titleNum).numberOfChildren() > 0) {
                newsRow = item.child(titleNum).child(0).label();
            } else if (item.child(descNum).numberOfChildren() > 0) {
                newsRow = item.child(descNum).child(0).label();
            } else {
                newsRow = "No title available";
            }
            //use else if because description should only be printed
            // if titleNum == -1 and description exists
        } else if (descNum != -1) {
            //check if description has a text child
            if (item.child(descNum).numberOfChildren() > 0) {
                newsRow = item.child(descNum).child(0).label();
            } else {
                newsRow = "No title available";
            }
        }
        //prints the link if one is present
        if (linkNum != -1) {
            out.println("<th><a href=\"" + item.child(linkNum).child(0).label()
                    + "\">" + newsRow + "</th>");
        }
        //close the row
        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter the URL of an RSS 2.0 news feed: ");
        String url = in.nextLine();
        /*
         * Read XML input and initialize XMLTree. If input is not legal XML,
         * this statement will fail.
         */
        XMLTree xml = new XMLTree1(url);
        while (!xml.label().equals("rss") && !xml.hasAttribute("version")
                && !xml.attributeValue("version").equals("2.0")) {
            out.println("Invalid RSS news feed.");
            out.println("Enter the URL of an RSS 2.0 news feed: ");
            url = in.nextLine();
            xml = new XMLTree1(url);
        }
        /*
         * user must enter name of html file
         */
        out.print("Enter the name of an html file: ");
        String fileName = in.nextLine();
        SimpleWriter file = new SimpleWriter1L(fileName);
        //now print html file
        outputHeader(xml.child(0), file);
        outputFooter(file);
        in.close();
        out.close();
        file.close();

    }

}
